// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjLFhCMng7IaFDNmZWRiO2LiOA8nAPlc',
    appId: '1:457499463543:web:c165a4b8468049a940db72',
    messagingSenderId: '457499463543',
    projectId: 'todo-mobxflutter',
    authDomain: 'todo-mobxflutter.firebaseapp.com',
    storageBucket: 'todo-mobxflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTUKt2Y8LkUGi977iKRArktFX5ztcgT2o',
    appId: '1:457499463543:android:ff534e3b7bd0f21b40db72',
    messagingSenderId: '457499463543',
    projectId: 'todo-mobxflutter',
    storageBucket: 'todo-mobxflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Q2H7nKIczhDz3dF2Zp995LgPGQWLs9I',
    appId: '1:457499463543:ios:ec3f6467c940622240db72',
    messagingSenderId: '457499463543',
    projectId: 'todo-mobxflutter',
    storageBucket: 'todo-mobxflutter.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Q2H7nKIczhDz3dF2Zp995LgPGQWLs9I',
    appId: '1:457499463543:ios:c332d3a257469e8240db72',
    messagingSenderId: '457499463543',
    projectId: 'todo-mobxflutter',
    storageBucket: 'todo-mobxflutter.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
